#!/urs/bin/env php
<?php

require __DIR__ . '/bootstrap.php';

use Symfony\Component\Console\Application;
use Plide\Config;
use Plide\Command;

$plideConsole = new Application();

$config = new Config;

$plideConsole->addCommands([
    new Command\CreateCommand($config),
    new Command\ShowCommand($config),
    new Command\ExportCommand($config),
]);

$plideConsole->run();
